Create makefile to install existing binaries, header files and
pkg-config data
--- Makefile	1970-01-01 01:00:00.000000000 +0100
+++ Makefile	2016-11-10 17:31:08.686722661 +0000
@@ -0,0 +1,23 @@
+all:	libtscam.pc
+
+%.pc:	%.pc.in
+	sed -e "s!@LIBDIR@!$(LIBDIR)!g" \
+		-e "s!@VERSION@!$(VERSION)!g" < $< > $@
+
+install:
+	mkdir -p $(LIBDIR) $(INCDIR) $(PKGCONFDIR) $(UDEVDIR)
+	case $(DEB_BUILD_ARCH) in \
+	i386) \
+		cp $(SRCDIR)/x86/libtscam*.so.$(VERSION) $(LIBDIR);; \
+	amd64) \
+		cp $(SRCDIR)/x64/libtscam*.so.$(VERSION) $(LIBDIR);; \
+	aarch64) \
+		cp $(SRCDIR)/arm64/libtscam*.so.$(VERSION) $(LIBDIR);; \
+	armhf) \
+		cp $(SRCDIR)/armhf/libtscam*.so.$(VERSION) $(LIBDIR);; \
+	esac
+	ln -sf libtscam.so.$(VERSION) $(LIBDIR)/libtscam.so.$(MAJOR_REV)
+	ln -sf libtscam.so.$(VERSION) $(LIBDIR)/libtscam.so
+	cp $(SRCDIR)/*.h $(INCDIR)
+	cp $(SRCDIR)/libtscam.pc $(PKGCONFDIR)
+	cp $(SRCDIR)/70-ts-cameras.rules $(UDEVDIR)
